# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('state_abbreviation', models.CharField(max_length=2)),
                ('vegetation_index', models.DecimalField(decimal_places=16, max_digits=16)),
                ('gdp', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
    ]
