# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
