# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_city_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='gdp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
