# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20170430_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageVegetationIndexPerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=16, max_digits=16)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CityGdpInYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='gdp',
        ),
        migrations.RemoveField(
            model_name='city',
            name='vegetation_index',
        ),
        migrations.AddField(
            model_name='citygdpinyear',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.City'),
        ),
        migrations.AddField(
            model_name='averagevegetationindexperyear',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.City'),
        ),
    ]
