# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_auto_20170430_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagevegetationindexperyear',
            name='value',
            field=models.DecimalField(decimal_places=20, max_digits=20),
        ),
    ]
