# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_auto_20170430_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagevegetationindexperyear',
            name='value',
            field=models.DecimalField(decimal_places=16, max_digits=18),
        ),
    ]
